combine_control_expr = false
comment_width = 80
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 80
format_strings = true
hex_literal_case = "Lower"
max_width = 80
imports_granularity = "Module"
normalize_comments = true
remove_nested_parens = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
wrap_comments = true
